function net = train_model()
% TRAIN_MODEL Trains AlexNet with transfer learning for face recognition

    root = fileparts(fileparts(mfilename('fullpath')));

    % Load preprocessed data
    disp('Preparing data...');
    [aug_train, aug_val, class_names] = preprocess_data();
    num_classes = numel(class_names);
    disp(['Training for ', num2str(num_classes), ' students...']);

    % Load pretrained AlexNet
    disp('Loading AlexNet...');
    net = alexnet;
    layers = net.Layers;

    % Replace last 3 layers for our number of students
    layers(end-2) = fullyConnectedLayer(num_classes, ...
        'WeightLearnRateFactor', 10, ...
        'BiasLearnRateFactor',   20, ...
        'Name', 'fc_attendance');

    layers(end-1) = softmaxLayer('Name', 'softmax_attendance');
    layers(end)   = classificationLayer('Name', 'output_attendance');

    % Training options — tuned for CPU
    options = trainingOptions('sgdm', ...
        'MiniBatchSize',        16, ...
        'MaxEpochs',            20, ...
        'InitialLearnRate',     1e-4, ...
        'LearnRateSchedule',    'piecewise', ...
        'LearnRateDropFactor',  0.1, ...
        'LearnRateDropPeriod',  10, ...
        'Momentum',             0.9, ...
        'L2Regularization',     1e-4, ...
        'ValidationData',       aug_val, ...
        'ValidationFrequency',  10, ...
        'Shuffle',              'every-epoch', ...
        'Verbose',              true, ...
        'Plots',                'training-progress', ...
        'ExecutionEnvironment', 'cpu');

    % Train
    disp('Training started — this will take a few minutes on CPU...');
    net = trainNetwork(aug_train, layers, options);

    % Save model
    model_path = fullfile(root, 'models', 'face_recognition_model.mat');
    save(model_path, 'net', 'class_names');
    disp(['Model saved to: ', model_path]);
end