import os
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from PyQt5.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel,
    QPushButton, QFrame, QMessageBox
)
from PyQt5.QtGui import QFont, QDesktopServices
from PyQt5.QtCore import QUrl
from utils.config import APP_VERSION, ROOT_DIR
from database.db_handler import reset_application_data

CARD_STYLE = """
    QFrame {
        background: #1C1E22;
        border-radius: 12px;
        border: 1px solid #2C3035;
    }
"""

BTN_PRIMARY = """
    QPushButton {
        background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #00D2FF, stop:1 #3A7BD5);
        color: white; border: none;
        border-radius: 8px; padding: 11px 24px;
        font-size: 13px; font-weight: bold;
    }
    QPushButton:hover { background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3A7BD5, stop:1 #00D2FF); }
"""

BTN_SECONDARY = """
    QPushButton {
        background: #2C3035; color: #E0E6ED; border: 1px solid #3A3F44;
        border-radius: 8px; padding: 11px 24px;
        font-size: 13px; font-weight: bold;
    }
    QPushButton:hover { background: #3A3F44; }
"""

BTN_DANGER = """
    QPushButton {
        background: #4B1F24; color: #FFD9DE; border: 1px solid #7A2D38;
        border-radius: 8px; padding: 11px 24px;
        font-size: 13px; font-weight: bold;
    }
    QPushButton:hover { background: #64252E; }
"""

class SettingsPage(QWidget):
    def __init__(self):
        super().__init__()
        self.setStyleSheet("background: #141619; color: #E0E6ED;")
        self._build_ui()

    def _build_ui(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(32, 32, 32, 32)
        layout.setSpacing(24)

        title = QLabel("System Settings")
        title.setFont(QFont("Segoe UI", 24, QFont.Bold))
        title.setStyleSheet("color: #FFFFFF;")
        layout.addWidget(title)

        subtitle = QLabel("Configure data paths, MATLAB models, and advanced training.")
        subtitle.setStyleSheet("color: #8B949E; font-size: 14px;")
        layout.addWidget(subtitle)

        # MATLAB / AI Settings Card
        matlab_card = QFrame()
        matlab_card.setStyleSheet(CARD_STYLE)
        matlab_layout = QVBoxLayout(matlab_card)
        matlab_layout.setContentsMargins(24, 24, 24, 24)
        matlab_layout.setSpacing(16)

        ml_title = QLabel("MATLAB CNN Integration")
        ml_title.setStyleSheet("color: #00D2FF; font-size: 16px; font-weight: bold; border: none;")
        matlab_layout.addWidget(ml_title)

        ml_desc = QLabel("Use these options to independently compile the AI model's structural data and train your custom CNN via MATLAB. (Utilizes the robust face crops natively generated by Python)")
        ml_desc.setStyleSheet("color: #8B949E; font-size: 13px; border: none; word-wrap: break-word;")
        matlab_layout.addWidget(ml_desc)

        btn_row = QHBoxLayout()
        btn_row.setSpacing(16)
        
        btn_open_data = QPushButton("View Training Data")
        btn_open_data.setStyleSheet(BTN_SECONDARY)
        btn_open_data.clicked.connect(self._open_data_folder)
        
        btn_open_matlab = QPushButton("Access MATLAB Scripts")
        btn_open_matlab.setStyleSheet(BTN_PRIMARY)
        btn_open_matlab.clicked.connect(self._launch_matlab)
        
        btn_row.addWidget(btn_open_data)
        btn_row.addWidget(btn_open_matlab)
        btn_row.addStretch()
        
        matlab_layout.addLayout(btn_row)
        layout.addWidget(matlab_card)

        reset_card = QFrame()
        reset_card.setStyleSheet(CARD_STYLE)
        reset_layout = QVBoxLayout(reset_card)
        reset_layout.setContentsMargins(24, 24, 24, 24)
        reset_layout.setSpacing(14)

        reset_title = QLabel("Data Management")
        reset_title.setStyleSheet("color: #FFFFFF; font-size: 16px; font-weight: bold; border: none;")
        reset_layout.addWidget(reset_title)

        reset_desc = QLabel(
            "Clear all enrolled students, attendance logs, and captured student images. "
            "This keeps the app files in place and only removes the live student/dashboard data."
        )
        reset_desc.setStyleSheet("color: #8B949E; font-size: 13px; border: none;")
        reset_desc.setWordWrap(True)
        reset_layout.addWidget(reset_desc)

        btn_reset = QPushButton("Clear Student Data")
        btn_reset.setStyleSheet(BTN_DANGER)
        btn_reset.clicked.connect(self._reset_all_data)
        reset_layout.addWidget(btn_reset)

        layout.addWidget(reset_card)

        # About / Info Card
        info_card = QFrame()
        info_card.setStyleSheet(CARD_STYLE)
        info_layout = QVBoxLayout(info_card)
        info_layout.setContentsMargins(24, 24, 24, 24)
        info_layout.setSpacing(12)

        info_title = QLabel("System Architecture Info")
        info_title.setStyleSheet("color: #FFFFFF; font-size: 16px; font-weight: bold; border: none;")
        info_layout.addWidget(info_title)

        infos = [
            f"Version: {APP_VERSION}",
            "Root Directory: " + ROOT_DIR,
            "Real-Time Face Recognition Engine: Python OpenCV & dlib (HOG/CNN Hybrid)",
            "Visual Adjustments: Automatically processes specs, glasses, and dynamic lighting securely.",
            "Backend Model Support: Deep Network Structures configurable via MATLAB plugins."
        ]
        for inf in infos:
            l = QLabel("• " + inf)
            l.setStyleSheet("color: #8B949E; font-size: 13px; border: none;")
            info_layout.addWidget(l)

        layout.addWidget(info_card)
        layout.addStretch()

    def _open_data_folder(self):
        data_path = os.path.join(ROOT_DIR, "data", "student_images")
        if not os.path.exists(data_path):
            os.makedirs(data_path, exist_ok=True)
        QDesktopServices.openUrl(QUrl.fromLocalFile(data_path))
        
    def _launch_matlab(self):
        matlab_folder = os.path.join(ROOT_DIR, "matlab")
        QDesktopServices.openUrl(QUrl.fromLocalFile(matlab_folder))

    def _reset_all_data(self):
        reply = QMessageBox.question(
            self,
            "Clear Student Data",
            "This will permanently remove all enrolled students, dashboard attendance records, and captured student images.\n\nDo you want to continue?",
            QMessageBox.Yes | QMessageBox.No,
            QMessageBox.No,
        )
        if reply != QMessageBox.Yes:
            return

        try:
            reset_application_data()
            QMessageBox.information(self, "Clear Complete", "All enrolled students and attendance data have been cleared.")
        except Exception as exc:
            QMessageBox.critical(self, "Clear Failed", f"Could not clear student data.\n\n{exc}")
